version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  jobapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: prabhjees/job_app:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO: create-drop
      SPRING_JPA_SHOW-SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_H2_CONSOLE_ENABLED: "false"
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data:
